apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dwn-server.fullname" . }}
  labels:
    {{- include "dwn-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "dwn-server.fullname" . }}
  selector:
    matchLabels:
      {{- include "dwn-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dwn-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: dwn-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.env.DS_PORT }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DS_PORT
              value: "{{ .Values.env.DS_PORT }}"
            - name: DS_MAX_RECORD_DATA_SIZE
              value: "{{ .Values.env.DS_MAX_RECORD_DATA_SIZE }}"
            - name: DS_WEBSOCKET_SERVER
              value: "{{ .Values.env.DS_WEBSOCKET_SERVER }}"
          volumeMounts:
            - name: data
              mountPath: /data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 13 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 13 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 13 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 13 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
